[workspace]
resolver = "2"
members = ["crates/roc_host", "crates/roc_host_lib", "crates/roc_host_bin"]

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1

[workspace.dependencies]
roc_std = { git = "https://github.com/roc-lang/roc.git", rev = "c47a8e9cdac8fe126045aed93e578dfebca11e06" }
