setup:
    meson setup generator build/generator
    @echo "--- Building generator ---"
    @meson compile -C build/generator
    @echo "--- Configuring main project ---"
    @PATH="{{invocation_directory()}}/build/generator:{{env_var('PATH')}}" meson setup src build

build:
    @echo "--- Building generator ---"
    @meson compile -C build/generator
    @echo "--- Building main project ---"
    @meson compile -C build

run: build
    ./build/plugged

watch:
    #!/bin/bash
    child_pid=""
    trap 'kill "$child_pid" 2>/dev/null; exit' SIGINT

    run_app() {
        if [ -n "$child_pid" ]; then
            kill "$child_pid" 2>/dev/null
        fi

        if just build; then
            clear
            ./build/plugged &
            child_pid=$!
        else
            echo "Build failed, not restarting application."
        fi
    }

    clear
    echo "Initial build..."
    run_app
    echo -e "\nWatching for changes in 'src/' and 'generator/'..."

    while inotifywait -q -r -e modify,create,delete src generator; do
        clear
        echo "Changes detected. Rebuilding..."
        run_app
        echo -e "\nWatching for changes in 'src/' and 'generator/'..."
    done
