executable(
  'iterators',
  'iterators.cpp',
  install: false,
  dependencies: [],
)

executable(
  'input',
  'input.cpp',
  install: false,
  dependencies: [],
)

executable(
  'triangle',
  'triangle.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'input_handling',
  'input_handling.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  're_input_handling',
  're_input_handling.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'triangle_2',
  'triangle_2.cpp',
  install: false,
  dependencies: [engine_dep],
)
