executable(
  'iterators',
  'iterators.cpp',
  install: false,
  dependencies: [],
)

executable(
  'input',
  'input.cpp',
  install: false,
  dependencies: [],
)

executable(
  'triangle',
  'triangle.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'input_handling',
  'input_handling.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  're_input_handling',
  're_input_handling.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'triangle_2',
  'triangle_2.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'sprite',
  'sprite.cpp',
  install: false,
  dependencies: [
    engine_dep,
  ],
)

executable(
  'edit_seq',
  'edit_seq.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'triangle_new_draw_api',
  'triangle_new_draw_api.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'browsertest',
  'browsertest.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'triangle_instanced',
  'triangle_instanced.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'physics',
  'physics.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'block_breaker',
  'block_breaker.cpp',
  install: false,
  dependencies: [engine_dep],
)

