[package]
name = "roc_host"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "app"

[lib]
name = "roc_host"

[dependencies]
roc_std.workspace = true
roc_app = { path = "../roc_app" }
libc = "0.2"
