version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: "2g"

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - selenium
