use bevy::{
    asset::{Asset, uuid},
    ecs::component::Component,
    math::Vec2,
    reflect::Reflect,
};
use serde::{Deserialize, Serialize};

mod animator;
pub mod loader;

/// Unique identifier for a critter instance
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Reflect)]
pub struct CritterId(pub uuid::Uuid);

impl CritterId {
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Reflect)]
pub struct UiAnimations {
    /// Looping preview shown in the adopt gallery.
    pub preview: usize,

    /// Played on the adoption confirmation
    pub celebrate: usize,

    /// Looping idle shown after adoption in the UI.
    pub idle: usize,
}

/// Stub for desktop window animations
// TODO: Expand later
#[derive(Debug, Clone, Serialize, Deserialize, Reflect)]
pub struct DesktopAnimations;

/// A critter definition loaded from a `.ron` manifest file.
/// Shipped critters live under `assets/critters/`
/// Downloaded critters are placed in the user data critters source (`critters://`).
#[derive(Debug, Clone, Serialize, Deserialize, Reflect, Asset)]
pub struct CritterDef {
    /// Stable string key used as a foreign key in saved `Preferences`.
    pub id: String,

    /// Default display name (user overridable per instance).
    pub name: String,

    /// Path to the `.glb` file, relative to the asset root.
    // TODO: Figure out how to handle this for downloaded critters.
    pub gltf: String,

    pub ui_animations: UiAnimations,

    pub desktop_animations: DesktopAnimations,
}

/// Registry of all available critter definitions.
/// Loaded once at startup; refreshed when new definitions are downloaded.
#[derive(Default, Debug, Clone, Reflect, Asset)]
pub struct CritterRegistry {
    pub defs: Vec<CritterDef>,
}

impl CritterRegistry {
    pub fn find(&self, id: &str) -> Option<&CritterDef> {
        self.defs.iter().find(|d| d.id == id)
    }
}

/// A critter instance owned by the user
#[derive(Debug, Clone, Serialize, Deserialize, Reflect, Component)]
pub struct Critter {
    pub id: CritterId,

    /// Foreign key into `CritterRegistry`.
    pub def_id: String,

    /// User-chosen display name.
    pub name: String,

    /// Last known window position on the assigned monitor (pixels from top-left).
    /// `top-left corner of the critter's desktop window in physical
    /// pixels, relative to the top-left of `monitor_fingerprint`'s display.
    pub position: Vec2,

    /// Size multiplier relative to the def's natural size.
    pub scale: f32,

    /// Window opacity, 0.0–1.0.
    pub opacity: f32,

    pub is_visible: bool,

    /// Fingerprint of the monitor this critter is assigned to.
    /// Generated by `generate_monitor_fingerprint`. Falls back to primary on mismatch.
    pub monitor_fingerprint: u64,
}
