[package]
name = "botnet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
json = "0.12.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json"] }
