bin := "./target/debug/botnet"

alias b := build
 
build:
  cargo build

broadcast:
  just build
  maelstrom test -w broadcast --bin {{bin}} --node-count 1 --time-limit 20 --rate 10

echo:
  just build
  maelstrom test -w echo --bin {{bin}} --node-count 1 --time-limit 10

unique-ids:
  just build
  maelstrom test -w unique-ids --bin {{bin}} --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition
