executable(
  'hello_world',
  'basics/hello_world.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'input',
  'input/input.cpp',
  install: false,
  dependencies: [],
)

executable(
  'triangle',
  'rendering/triangle.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'sprite',
  'rendering/sprite.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'tetris',
  'games/tetris.cpp',
  install: false,
  dependencies: [engine_dep],
)

executable(
  'block_breaker',
  'games/block_breaker.cpp',
  install: false,
  dependencies: [engine_dep],
)
