use std::hash::{DefaultHasher, Hash, Hasher};

use bevy::{
    asset::{Asset, AssetLoadFailedEvent, AssetLoader, AssetPath, AsyncReadExt},
    prelude::*,
    reflect::Reflect,
    scene::ron,
    tasks::AsyncComputeTaskPool,
    window::Monitor,
};
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::critter::{Critter, CritterRegistry};

#[derive(Clone, Debug, Serialize, Deserialize, Reflect, Asset)]
pub struct Preferences {
    /// Version for migrations.
    pub version: String,

    /// Active theme.
    pub theme: crate::ui::palette::Palette,

    /// Per-monitor settings, keyed by fingerprint.
    pub monitors: Vec<MonitorSettings>,

    /// Application-level settings.
    pub app_settings: ApplicationSettings,

    /// All owned critters. Single source of truth for critter state.
    pub critters: Vec<Critter>,

    /// Global critter settings.
    pub global_critter_settings: GlobalCritterSettings,

    /// True on first launch; triggers the onboarding flow.
    pub first_start: bool,
}

impl Default for Preferences {
    fn default() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            theme: Default::default(),
            monitors: Default::default(),
            app_settings: Default::default(),
            critters: Default::default(),
            global_critter_settings: Default::default(),
            first_start: true,
        }
    }
}

/// Per-monitor user configuration
#[derive(Debug, Default, Clone, Serialize, Deserialize, Reflect)]
pub struct MonitorSettings {
    /// Stable fingerprint generated by `generate_monitor_fingerprint`.
    pub fingerprint: u64,

    /// Whether critters are allowed on this monitor.
    pub enabled: bool,

    /// Exclusion zones where critters shouldn't wander.
    /// Each tuple is (x, y, width, height) as fractions of the monitor size.
    pub exclusion_zones: Vec<(f32, f32, f32, f32)>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Reflect)]
pub struct ApplicationSettings {
    pub start_on_boot: bool,

    pub start_minimized: bool,

    pub show_tray_icon: bool,

    pub close_to_tray: bool,

    pub check_updates: bool,

    pub send_analytics: bool,
}

impl Default for ApplicationSettings {
    fn default() -> Self {
        Self {
            start_on_boot: false,
            start_minimized: false,
            show_tray_icon: true,
            close_to_tray: true,
            check_updates: true,
            send_analytics: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Reflect)]
pub struct GlobalCritterSettings {
    pub interactions_enabled: bool,

    pub display_critter_name_on_hover: bool,

    pub sound_enabled: bool,
}

impl Default for GlobalCritterSettings {
    fn default() -> Self {
        Self {
            interactions_enabled: true,
            display_critter_name_on_hover: true,
            sound_enabled: false,
        }
    }
}

#[derive(Error, Debug)]
#[non_exhaustive]
pub enum PreferencesLoadError {
    #[error("IO Error")]
    IoError(#[from] std::io::Error),
    #[error("Deserialization Error")]
    DeserializationError(#[from] ron::de::SpannedError),
}

pub struct PreferencesLoader;

impl AssetLoader for PreferencesLoader {
    type Asset = Preferences;
    type Settings = ();
    type Error = PreferencesLoadError;

    fn load(
        &self,
        reader: &mut dyn bevy::asset::io::Reader,
        _: &Self::Settings,
        _: &mut bevy::asset::LoadContext,
    ) -> impl bevy::tasks::ConditionalSendFuture<Output = Result<Self::Asset, Self::Error>> {
        async {
            let mut buf = String::new();
            reader.read_to_string(&mut buf).await?;
            Ok(ron::from_str(&buf)?)
        }
    }
}

#[derive(Resource)]
pub struct PreferencesHandle(pub Handle<Preferences>);

#[derive(Resource)]
pub struct RegistryHandle(pub Handle<crate::critter::CritterRegistry>);

pub fn start_loading_assets(mut commands: Commands, asset_server: Res<AssetServer>) {
    let prefs: Handle<Preferences> = asset_server.load("appdata://preferences.ron");
    commands.insert_resource(PreferencesHandle(prefs));

    let registry: Handle<crate::critter::CritterRegistry> =
        asset_server.load("critters://manifest.critter.ron");
    commands.insert_resource(RegistryHandle(registry));
}

pub fn create_default_prefs_on_fail(
    prefs_handle: Res<PreferencesHandle>,
    mut prefs_store: ResMut<Assets<Preferences>>,
    mut events: EventReader<AssetLoadFailedEvent<Preferences>>,
) {
    if events.read().next().is_some() {
        info!("Preferences not found — creating defaults");
        prefs_store.insert(&prefs_handle.0, Preferences::default());
    }
}

pub fn unpack_default_critter_manifest(
    registry_handle: Res<RegistryHandle>,
    mut registry_store: ResMut<Assets<crate::critter::CritterRegistry>>,
    mut events: EventReader<AssetLoadFailedEvent<crate::critter::CritterRegistry>>,
) {
    if events.read().next().is_some() {
        info!("Unpacking default critter manifest");
        registry_store.insert(&registry_handle.0, CritterRegistry::default());
    }
}

/// Transitions to `AppState::Running` once both required assets are loaded.
pub fn check_loading_complete(
    prefs_handle: Res<PreferencesHandle>,
    registry_handle: Res<RegistryHandle>,
    prefs_store: Res<Assets<Preferences>>,
    registry_store: Res<Assets<crate::critter::CritterRegistry>>,
    mut next: ResMut<NextState<crate::AppState>>,
) {
    if prefs_store.get(&prefs_handle.0).is_some()
        && registry_store.get(&registry_handle.0).is_some()
    {
        next.set(crate::AppState::Running);
    }
}

pub fn query_monitor_info(
    monitors: Query<&Monitor>,
    prefs_handle: Res<PreferencesHandle>,
    mut prefs_store: ResMut<Assets<Preferences>>,
) {
    for monitor in &monitors {
        let Some(prefs) = prefs_store.get_mut(&prefs_handle.0) else {
            return;
        };
        let fp = generate_monitor_fingerprint(monitor);
        if prefs.monitors.iter().all(|m| m.fingerprint != fp) {
            prefs.monitors.push(MonitorSettings {
                fingerprint: fp,
                enabled: true,
                exclusion_zones: Vec::new(),
            });
        }
    }
}

pub fn save_preferences_on_exit(
    prefs_handle: Res<PreferencesHandle>,
    prefs_store: Res<Assets<Preferences>>,
    asset_server: Res<AssetServer>,
    mut app_exit_events: EventReader<AppExit>,
) {
    if app_exit_events.read().next().is_some() {
        if let Some(prefs) = prefs_store.get(&prefs_handle.0) {
            let mut prefs = prefs.clone();
            prefs.first_start = false;

            AsyncComputeTaskPool::get()
                .spawn({
                    let asset_server = asset_server.clone();
                    let serialized =
                        ron::ser::to_string_pretty(&prefs, ron::ser::PrettyConfig::new())
                            .expect("Unable to serialize preferences");

                    async move {
                        let asset_path = AssetPath::parse("appdata://preferences.ron");
                        let path = asset_path.path();
                        let source = asset_server.get_source(asset_path.source()).unwrap();
                        let writer = source.writer().unwrap();
                        writer
                            .write_bytes(path, serialized.as_bytes())
                            .await
                            .expect("Unable to write preferences");
                    }
                })
                .detach();
        }
    }
}

/// Generates a stable fingerprint for a monitor. Position is quantised to
/// reduce sensitivity to minor OS-reported jitter between sessions.
pub fn generate_monitor_fingerprint(monitor: &Monitor) -> u64 {
    let mut hasher = DefaultHasher::new();
    monitor.physical_height.hash(&mut hasher);
    monitor.physical_width.hash(&mut hasher);
    let qx = (monitor.physical_position.x / 10) * 10;
    let qy = (monitor.physical_position.y / 10) * 10;
    qx.hash(&mut hasher);
    qy.hash(&mut hasher);
    hasher.finish()
}
