setup:
    #!/usr/bin/env bash
    set -euxo pipefail

    echo "Cleaning old build directory..."
    # rm -rf build

    echo "Setting up build directories..."
    meson setup build/debug
    
    meson setup --buildtype=release build/release
    meson setup --cross-file=./wasm32.ini \
        "-Dc_args=['-O0','-g']" \
        "-Dcpp_args=['-O0','-g']" \
        "-Dc_link_args=['-gsource-map','-sASSERTIONS=1','-sSAFE_HEAP=1','-sSTACK_OVERFLOW_CHECK=2','-sDISABLE_EXCEPTION_CATCHING=0']" \
        "-Dcpp_link_args=['-gsource-map','-sASSERTIONS=1','-sSAFE_HEAP=1','-sSTACK_OVERFLOW_CHECK=2','-sDISABLE_EXCEPTION_CATCHING=0']" \
        --wipe build/wasm32/debug
    meson setup --cross-file=./wasm32.ini --buildtype=release build/wasm32/release

serve binary_name:
    #!/usr/bin/env bash
    set -euxo pipefail

    echo "Compiling {{binary_name}} for wasm..."
    meson compile -C build/wasm32/debug {{binary_name}}

    echo "Preparing public directory..."
    mkdir -p public
    cp build/wasm32/debug/labs/{{binary_name}}.js public/
    cp build/wasm32/debug/labs/{{binary_name}}.wasm public/
    cp build/wasm32/debug/labs/{{binary_name}}.wasm.map public/

    echo "Generating index.html..."
    cat > public/index.html <<EOF
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{binary_name}}</title>
    </head>
    <body>
        <script src="{{binary_name}}.js"></script>
    </body>
    </html>
    EOF

    echo "Starting server at http://localhost:8080"
    
    # Assumes static-web-server is installed 
    static-web-server --port 8080 -d public
    

watch_lab binary_name:
    #!/bin/bash
    # set -euxo pipefail; 
    
    child_pid=""
    trap 'kill $child_pid 2>/dev/null; exit' SIGINT
    
    run() {
        if [ -n "$child_pid" ]; then
            kill $child_pid 2>/dev/null
        fi

        meson compile -C build {{binary_name}}
        if [ $? -eq 0 ]; then
            clear
            ./build/labs/{{binary_name}} &
            child_pid=$!
        fi
    }
    
    clear
    echo "Building..."
    run
    echo -e "\n"
    
    while inotifywait -q -e modify labs/{{binary_name}}.cpp; do
        clear
        echo "Rebuilding..."
        run
    done
