default:
    @echo "Available recipes: setup, setup-debug, setup-release, serve <binary_name>, watch_lab <binary_name>"

setup: setup-debug setup-release

setup-debug:
    #!/usr/bin/env bash
    set -euxo pipefail

    echo "Setting up debug build directories..."
    meson setup build/debug
    meson setup --cross-file=./wasm32-debug.ini --wipe build/wasm32/debug

setup-release:
    #!/usr/bin/env bash
    set -euxo pipefail

    echo "Setting up release build directories..."
    meson setup --buildtype=release build/release
    meson setup --cross-file=./wasm32-release.ini --buildtype=release --wipe build/wasm32/release

serve binary_name:
    #!/usr/bin/env bash
    set -euxo pipefail

    echo "Compiling {{binary_name}} for wasm..."
    meson compile -C build/wasm32/debug {{binary_name}}

    echo "Preparing public directory..."
    mkdir -p public
    cp build/wasm32/debug/labs/{{binary_name}}.js public/
    cp build/wasm32/debug/labs/{{binary_name}}.wasm public/
    cp build/wasm32/debug/labs/{{binary_name}}.wasm.map public/

    echo "Generating index.html..."
    cat > public/index.html <<EOF
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{binary_name}}</title>
    </head>
    <body>
        <script src="{{binary_name}}.js"></script>
    </body>
    </html>
    EOF

    echo "Starting server at http://localhost:8080"
    
    # Assumes static-web-server is installed 
    static-web-server --config-file sws-config.toml

watch_lab binary_name:
    #!/bin/bash
    # set -euxo pipefail; 
    
    child_pid=""
    trap 'kill $child_pid 2>/dev/null; exit' SIGINT
    
    run() {
        if [ -n "$child_pid" ]; then
            kill $child_pid 2>/dev/null
        fi

        meson compile -C build/debug {{binary_name}}
        if [ $? -eq 0 ]; then
            clear
    
            # BUG:  Running in the background redirects IO which means:
            #   1. IO is not detected as a tty and the interactive programs will fail
            #   2. It is difficult to run interactive programs in the background and rendering
            #    often fails in unexpected ways
            #  TODO: Explore how to solve this
            ./build/debug/labs/{{binary_name}} & 
            child_pid=$!
        fi
    }
    
    clear
    echo "Building..."
    run
    echo -e "\n"
    
    while inotifywait -q -e modify labs/{{binary_name}}.cpp; do
        clear
        echo "Rebuilding..."
        run
    done
