# ref: https://github.com/mesonbuild/meson/blob/master/cross/wasm.txt
[binaries]
c = 'emcc'
cpp = 'em++'
ar = 'emar'
wasm = '/wabt/bin/wasm2wat'
wat = '/wabt/bin/wat2wasm'

[built-in options]
default_library = 'static'
c_args = ['-O3']
c_link_args = ['-s','EXPORT_ALL=1', '-s', 'ENVIRONMENT=web', '-s', 'DISABLE_EXCEPTION_CATCHING=0', '-s', 'EXPORTED_RUNTIME_METHODS=["HEAPU8", "ccall", "cwrap"]']
cpp_args = ['-O3']
cpp_link_args = ['-s', 'EXPORT_ALL=1', '-s', 'ENVIRONMENT=web', '-s', 'DISABLE_EXCEPTION_CATCHING=0', '-s', 'EXPORTED_RUNTIME_METHODS=["HEAPU8", "ccall", "cwrap"]']

[properties]
static_library_suffix = 'la'
shared_library_suffix = 'js'
shared_module_suffix = 'js'

[host_machine]
system = 'emscripten'
cpu_family = 'wasm32'
cpu = 'wasm'
endian = 'little'
