[package]
name = "lovable"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", default-features = false, features = [
  "bevy_log",
  "bevy_asset",
  "bevy_winit",
  "bevy_window",
  "bevy_render",
  "png",
  "bevy_gltf",
  "bevy_scene",
  "bevy_animation",
] }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
