[package]
name = "lovable"
version = "0.1.0"
edition = "2024"

[package.metadata.packager]
before-packaging-command = "cargo build --release"
product-name = "Lovable"
identifier = "com.sandboxedideas.lovable"
version = "0.1.0"
icons = ["assets/icons/icon.png"]
resources = [{ src = "assets/", target = "assets" }] 

[dependencies]
auto-launch = "0.6.0"
bevy = "0.16.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
tray-icon = "0.21.3"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
strip = "debuginfo" 
opt-level = 3
codegen-units = 1
incremental = false
debug = false
